### PR TITLE
Fix directories being ignored.

### PR DESCRIPTION
**Pull request by LexLythius**
Same as in gulp-chown.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for the pull request :)

I think this should follow `gulp.dest` and have a separate option for `dirMode` as it seems that's needed for some reason: https://github.com/wearefractal/vinyl-fs/issues/35 Could maybe have it as a second argument to `chmod`.

**Comment by sindresorhus** [comment]
@LexLythius Still interested?

**Comment by LexLythius** [comment]
@sindresorhus Sorry I missed your last update. Honestly, right now I have my hands more than full to take care of this and will remain so for a couple weeks.
If you don't mind keeping this PR open I can look into it again later. Or just close it and I can always do this a bit later and open a new PR.

**Comment by sindresorhus** [comment]
Sure, no rush ;)

**Comment by sindresorhus** [comment]
Closing for lack of progress. Opened an issue so it won't be forgotten: #6.

**Pull request closed without merging**
